
---
server:
  port: 8081
---
server:
  port: 8082

#不同的环境开发,生产,测试,对应的profiles不同
# spring.profiles.active: prod
#spring:
#  profiles:
#    active: dev
---
server:
  port: 8084
spring:
  profiles: prod


  path: /hello


#  可以利用占位符来引用一些变量
person:
  lastName: Coolkie${random.uuid}
  age: ${random.int}
  boss: true
  birth: 2021/9/14
  maps:
    k1: v1
    k2: v2
  lists:
    - 张三
    - 李四
  dog:
    name: ${person.lastName}_fuck
    age: 2